// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXmORGXyHbN5s5C9YmSsyBbdMIjMx98D8',
    appId: '1:721153410908:web:8775e9a26db19144426399',
    messagingSenderId: '721153410908',
    projectId: 'khmerlearning-y4s1',
    authDomain: 'khmerlearning-y4s1.firebaseapp.com',
    storageBucket: 'khmerlearning-y4s1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPVAcdFqL9_XAuT6RjmiZNZJI2hTk5DZ0',
    appId: '1:721153410908:android:e03b44e310b06407426399',
    messagingSenderId: '721153410908',
    projectId: 'khmerlearning-y4s1',
    storageBucket: 'khmerlearning-y4s1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd69nGDBjs-9coqF4Lynu9tAN1C4WLn9w',
    appId: '1:721153410908:ios:33d37880d8ecaf9d426399',
    messagingSenderId: '721153410908',
    projectId: 'khmerlearning-y4s1',
    storageBucket: 'khmerlearning-y4s1.firebasestorage.app',
    iosBundleId: 'com.example.khmerlearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd69nGDBjs-9coqF4Lynu9tAN1C4WLn9w',
    appId: '1:721153410908:ios:33d37880d8ecaf9d426399',
    messagingSenderId: '721153410908',
    projectId: 'khmerlearning-y4s1',
    storageBucket: 'khmerlearning-y4s1.firebasestorage.app',
    iosBundleId: 'com.example.khmerlearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXmORGXyHbN5s5C9YmSsyBbdMIjMx98D8',
    appId: '1:721153410908:web:21746e74312f0e01426399',
    messagingSenderId: '721153410908',
    projectId: 'khmerlearning-y4s1',
    authDomain: 'khmerlearning-y4s1.firebaseapp.com',
    storageBucket: 'khmerlearning-y4s1.firebasestorage.app',
  );
}
